require('./users');
// require('./posts');
// require('./postComments');
// require('./postCategories');
// require('./galleries');
// require('./enquiries');
// require('./everything');
require('./homepage');
require('./navbar');
require('./menu');
require('./footer');
require('./company-profile');
require('./companyinfolistmenu');
require('./mangementteam');
require('./differentiator');
require('./career');
require('./partner');
require('./softwareproduct');
require('./listingmenu');
require('./consultingservice');
require('./msp');
require('./specializedanalyse');
require('./offering');
require('./technologyresale');
require('./contactform');